//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyAbroad.DynamicLoading.Resources.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CountryCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudyAbroad.DynamicLoading.Resources.Content.CountryCodes", typeof(CountryCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF AFG 004 
        ///AX ALA 248 
        ///AL ALB 008 
        ///DZ DZA 012 
        ///AS ASM 016 
        ///AD AND 020 
        ///AO AGO 024 
        ///AI AIA 660 
        ///AQ ATA 010 
        ///AG ATG 028 
        ///AR ARG 032 
        ///AM ARM 051 
        ///AW ABW 533 
        ///AU AUS 036 
        ///AT AUT 040 
        ///AZ AZE 031 
        ///BS BHS 044 
        ///BH BHR 048 
        ///BD BGD 050 
        ///BB BRB 052 
        ///BY BLR 112 
        ///BE BEL 056 
        ///BZ BLZ 084 
        ///BJ BEN 204 
        ///BM BMU 060 
        ///BT BTN 064 
        ///BO BOL 068 
        ///BA BIH 070 
        ///BW BWA 072 
        ///BV BVT 074 
        ///BR BRA 076 
        ///VG VGB 092 
        ///IO IOT 086 
        ///BN BRN 096 
        ///BG BGR 100 
        ///BF BFA 854 
        ///BI BDI 108 
        ///KH KHM 116 
        ///CM CMR 120 
        ///CA CA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ISOCountryCodes {
            get {
                return ResourceManager.GetString("ISOCountryCodes", resourceCulture);
            }
        }
    }
}
