//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyAbroad.DynamicLoading.Resources.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Uris {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Uris() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudyAbroad.DynamicLoading.Resources.Content.Uris", typeof(Uris).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://climatedataapi.worldbank.org/climateweb/rest/v1/country/cru/pr/month/.
        /// </summary>
        internal static string DataBankClimatePrecipititaion {
            get {
                return ResourceManager.GetString("DataBankClimatePrecipititaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://climatedataapi.worldbank.org/climateweb/rest/v1/country/cru/tas/month/.
        /// </summary>
        internal static string DataBankClimateTemperature {
            get {
                return ResourceManager.GetString("DataBankClimateTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyAZNNM5xSLRyaBgQvATf1uKKKMznPVDz0A.
        /// </summary>
        internal static string FreebaseApiKey {
            get {
                return ResourceManager.GetString("FreebaseApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyAUkaIrq3REno9KuuFEffuPOWA2DOoAnus.
        /// </summary>
        internal static string FreebaseApiServer {
            get {
                return ResourceManager.GetString("FreebaseApiServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://img.freebase.com/api/trans/image_thumb/.
        /// </summary>
        internal static string FreebaseImages {
            get {
                return ResourceManager.GetString("FreebaseImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.googleapis.com/freebase/v1/mqlread.
        /// </summary>
        internal static string FreebaseQuery {
            get {
                return ResourceManager.GetString("FreebaseQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.googleapis.com/freebase/v1/image.
        /// </summary>
        internal static string FreebaseRawImage {
            get {
                return ResourceManager.GetString("FreebaseRawImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.googleapis.com/freebase/v1/text/.
        /// </summary>
        internal static string FreebaseRawText {
            get {
                return ResourceManager.GetString("FreebaseRawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.googleapis.com/freebase/v1/search.
        /// </summary>
        internal static string FreebaseSearch {
            get {
                return ResourceManager.GetString("FreebaseSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to poli_milano_430.
        /// </summary>
        internal static string NumbeoApiKey {
            get {
                return ResourceManager.GetString("NumbeoApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.numbeo.com/api/city_prices.
        /// </summary>
        internal static string NumbeoCityPrices {
            get {
                return ResourceManager.GetString("NumbeoCityPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://en.wikipedia.org/wiki/index.html?curid=.
        /// </summary>
        internal static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
    }
}
