//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyAbroad.DataAccess.Resources.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConnStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConnStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudyAbroad.DataAccess.Resources.Content.ConnStrings", typeof(ConnStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=BRANIMIRASUS\SQLEXPRESS;Initial Catalog=StudyAbroad;Integrated Security=True;Pooling=True;Max Pool Size=500;.
        /// </summary>
        internal static string BranimirBigPool {
            get {
                return ResourceManager.GetString("BranimirBigPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=BRANIMIRASUS\SQLEXPRESS;Initial Catalog=StudyAbroad;Integrated Security=True;.
        /// </summary>
        internal static string BranimirDefault {
            get {
                return ResourceManager.GetString("BranimirDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=localhost;Initial Catalog=StudyAbroad;Persist Security Info=True;User ID=studyabroad;Password=studyabroad.
        /// </summary>
        internal static string DataBaseLocal {
            get {
                return ResourceManager.GetString("DataBaseLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=localhost;Initial Catalog=StudyAbroad;Persist Security Info=True;User ID=studyabroad;Password=studyabroad;Pooling=True;Max Pool Size=200;.
        /// </summary>
        internal static string DataBaseLocalBigPool {
            get {
                return ResourceManager.GetString("DataBaseLocalBigPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=studyabroad.zapto.org;Initial Catalog=StudyAbroad;Persist Security Info=True;User ID=studyabroad;Password=studyabroad.
        /// </summary>
        internal static string DataBaseRemote {
            get {
                return ResourceManager.GetString("DataBaseRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=studyabroad.zapto.org;Initial Catalog=StudyAbroad;Persist Security Info=True;User ID=studyabroad;Password=studyabroad;Pooling=True;Max Pool Size=10000;.
        /// </summary>
        internal static string DataBaseRemoteBigPool {
            get {
                return ResourceManager.GetString("DataBaseRemoteBigPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=bakakata-pc\sqlexpress;Initial Catalog=StudyAbroad;Integrated Security=True.
        /// </summary>
        internal static string Katarina {
            get {
                return ResourceManager.GetString("Katarina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=localhost;Initial Catalog=Test;Persist Security Info=True;User ID=studyabroad;Password=studyabroad.
        /// </summary>
        internal static string TestDataBaseLocal {
            get {
                return ResourceManager.GetString("TestDataBaseLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=studyabroad.zapto.org;Initial Catalog=Test;Persist Security Info=True;User ID=studyabroad;Password=studyabroad.
        /// </summary>
        internal static string TestDataBaseRemote {
            get {
                return ResourceManager.GetString("TestDataBaseRemote", resourceCulture);
            }
        }
    }
}
