//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyAbroad.DataAccess.Resources.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IsoLocations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IsoLocations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudyAbroad.DataAccess.Resources.Content.IsoLocations", typeof(IsoLocations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002-Africa#015-Northern Africa:DZ,EG,EH,LY,MA,SD,TN|011-Western Africa:BF,BJ,CI,CV,GH,GM,GN,GW,LR,ML,MR,NE,NG,SH,SL,SN,TG|017-Middle Africa:AO,CD,ZR,CF,CG,CM,GA,GQ,ST,TD|014-Eastern Africa:BI,DJ,ER,ET,KE,KM,MG,MU,MW,MZ,RE,RW,SC,SO,TZ,UG,YT,ZM,ZW|018-Southern Africa:BW,LS,NA,SZ,ZA&amp;150-Europe#154-Northern Europe:GG,JE,AX,DK,EE,FI,FO,GB,IE,IM,IS,LT,LV,NO,SE,SJ|155-Western Europe:AT,BE,CH,DE,DD,FR,FX,LI,LU,MC,NL|151-Eastern Europe:BG,BY,CZ,HU,MD,PL,RO,RU,SU,SK,UA|039-Southern Europe:AD,AL,BA,ES,GI,GR,HR,IT,ME,M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US-AL:Alabama#US-AK:Alaska#US-AS:American Samoa#US-AZ:Arizona#US-AR:Arkansas#US-CA:California#US-CO:Colorado#US-CT:Connecticut#US-DE:Delaware#US-DC:District of Columbia#US-FL:Florida#US-GA:Georgia#US-GU:Guam#US-HI:Hawaii#US-ID:Idaho#US-IL:Illinois#US-IN:Indiana#US-IA:Iowa#US-KS:Kansas#US-KY:Kentucky#US-LA:Louisiana#US-ME:Maine#US-MD:Maryland#US-MA:Massachusetts#US-MI:Michigan#US-MN:Minnesota#US-MS:Mississippi#US-MO:Missouri#US-MT:Montana#US-NE:Nebraska#US-NV:Nevada#US-NH:New Hampshire#US-NJ:New Jersey#US-NM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
    }
}
