//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyAbroad.DataAccess.Resources.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Uris {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Uris() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudyAbroad.DataAccess.Resources.Content.Uris", typeof(Uris).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4icu.org/.
        /// </summary>
        internal static string IcuBase {
            get {
                return ResourceManager.GetString("IcuBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4icu.org/topAfrica/.
        /// </summary>
        internal static string IcuTopAfrica {
            get {
                return ResourceManager.GetString("IcuTopAfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4icu.org/topAsia/.
        /// </summary>
        internal static string IcuTopAsia {
            get {
                return ResourceManager.GetString("IcuTopAsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4icu.org/topEurope/.
        /// </summary>
        internal static string IcuTopEurope {
            get {
                return ResourceManager.GetString("IcuTopEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4icu.org/topNorth-America/.
        /// </summary>
        internal static string IcuTopNAmerica {
            get {
                return ResourceManager.GetString("IcuTopNAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4icu.org/topOceania/.
        /// </summary>
        internal static string IcuTopOceania {
            get {
                return ResourceManager.GetString("IcuTopOceania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4icu.org/topLatin-America/.
        /// </summary>
        internal static string IcuTopSAmerica {
            get {
                return ResourceManager.GetString("IcuTopSAmerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.4icu.org/top200/.
        /// </summary>
        internal static string IcuTopWorld {
            get {
                return ResourceManager.GetString("IcuTopWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.iso.org/iso/home/standards/country_codes/country_names_and_code_elements_xml.htm.
        /// </summary>
        internal static string IsoLocationsXml {
            get {
                return ResourceManager.GetString("IsoLocationsXml", resourceCulture);
            }
        }
    }
}
